### PR TITLE
Update lita-google-image and configs

### PR DESCRIPTION
**Pull request by hlcfan**
> Not sure is it a good idea to put the API key into a public repo?

### CODE REVIEW

**Comment by adamzaninovich** [comment]
@hlcfan I'll put the keys in an env variable on heroku. Where can I generate a new keys?

**Comment by adamzaninovich** [comment]
@hlcfan can you please update the config to

```
# Google custom image search
config.handlers.google_images.google_cse_id = ENV["GOOGLE_IMG_ID"]
config.handlers.google_images.google_cse_key = ENV["GOOGLE_IMG_KEY"]
config.handlers.google_images.safe_search = :medium
```

**Comment by hlcfan** [comment]
@adamzaninovich here you go.

**Comment by adamzaninovich** [comment]
Cowboy merging this

**Pull request merged**
